CREATE TABLE topicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    mensagem TEXT NOT NULL,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL,

    autor_id BIGINT NOT NULL,
    curso_id BIGINT NOT NULL,

    CONSTRAINT fk_topico_autor
        FOREIGN KEY (autor_id)
        REFERENCES usuarios(id),

    CONSTRAINT fk_topico_curso
        FOREIGN KEY (curso_id)
        REFERENCES cursos(id)
);