CREATE TABLE respostas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem TEXT NOT NULL,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    solucao BOOLEAN DEFAULT FALSE,

    topico_id BIGINT NOT NULL,
    autor_id BIGINT NOT NULL,

    CONSTRAINT fk_resposta_topico
        FOREIGN KEY (topico_id)
        REFERENCES topicos(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_resposta_autor
        FOREIGN KEY (autor_id)
        REFERENCES usuarios(id)
);